# Generated by Django 5.0.4 on 2024-05-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='uniquename',
            field=models.CharField(default='', max_length=100),
        ),
    ]
