# Generated by Django 5.0.4 on 2024-05-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_sub_category_uniquename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=200)),
                ('categories', models.ManyToManyField(to='shop.category')),
            ],
        ),
    ]
