# Generated by Django 5.0.4 on 2024-05-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='sub_categories',
            field=models.ManyToManyField(to='shop.sub_category'),
        ),
    ]
