# Generated by Django 5.0.4 on 2024-05-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_color_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='Color',
            new_name='color',
        ),
    ]
