# Generated by Django 5.0.4 on 2024-05-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='stock',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
